### ISSUE TITLE
Support #pragma mark

### ISSUE THREAD

**Issue by ttsshh1990** [everdrone/mark-meta-comments#1]
Please add the support to "#pragma mark - MARK" style marks if possible:

    const pragmaMarkRegex =
      /^\#pragma mark - (.*)$/gm;

    match = null;
    while ((match = pragmaMarkRegex.exec(text))) {
      const startPos = activeEditor.document.positionAt(match.index);
      const endPos = activeEditor.document.positionAt(
        match.index + match[0].length
      );

      const decoration = {
        range: new vscode.Range(startPos, endPos),
      };

      lineMarks.push(decoration);
      marksBold.push(decoration);
    }

**Comment by everdrone** [comment]
Hi! I'm not familiar with #pragma mark

I've read that in XCode it creates a bookmark in the symbol navigator, is that right?

Does it also have any visual differences compared to other comments/preprocs?

**Comment by ttsshh1990** [comment]
yes it has the similar visual difference as what this plugin is doing with "// MARK: - ":

<img width="2022" alt="Screen Shot 2022-09-06 at 10 53 09 AM" src="https://user-images.githubusercontent.com/8973422/188705384-e43116dc-f51e-4275-9ed2-a4862112ef16.png">

so to add the pattern "#pragma makr - " to the match list should work

**Comment by ttsshh1990** [comment]
Maybe a better example here:
<img width="2017" alt="Screen Shot 2022-09-06 at 10 57 23 AM" src="https://user-images.githubusercontent.com/8973422/188706077-6bf9265d-f17d-4408-9aee-d81e6b7e1b26.png">

**Comment by everdrone** [comment]
`#pragma mark -` comments have been added with the current release (v0.2.0)

Closing
